// app/layout.tsx or wherever RootLayout is

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import Footer from "@/components/mdb/components/layout/Footer";
import NavbarWrapper from "@/components/mdb/components/layout/NavbarWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className + " antialiased"}>
        <NavbarWrapper>{children}</NavbarWrapper>
        <Footer
          brand={<span className="font-mono text-brand">shadyt-ui</span>}
          links={[
            { label: "Docs", href: "/docs" },
            { label: "GitHub", href: "https://github.com/Cstannahill" },
            { label: "License", href: "/license" },
          ]}
          copyright="2025 Christian Tannahill"
        />
      </body>
    </html>
  );
}
